### ISSUE TITLE
power-select-multiple

### ISSUE THREAD

**Issue by teddycoleman** [kaliber5/ember-bootstrap-power-select#1]
So far, ember-bootstrap and ember-boostrap-power-select have been working pretty well for me.  Is there support for power-select-multiple? When I try to use it, I don't see any options.

Let me know - thanks!

```        
{{form.element controlType="power-select-multiple" property="flags" label="Choose" options=flagFilters optionLabelPath="label" dropdownClass="in-modal-dropdown"}}
```

![image](https://user-images.githubusercontent.com/15386324/27091518-3923434e-5015-11e7-943e-daa624a8f0e7.png)

Works fine though if I use power-select: 
```
{{form.element controlType="power-select" property="flags" label="Choose" options=flagFilters optionLabelPath="label" dropdownClass="in-modal-dropdown"}}
```

**Comment by simonihmig** [comment]
No, this is indeed not supported currently. 

Would not be too hard to implement I think, just needs an implementation of 
`bs-form/element/control/power-select-multiple` component similar to the existing 
`bs-form/element/control/power-select`. A PR would certainly be highly appreciated! ;)

**Comment by teddycoleman** [comment]
ok thanks, will close for now. fyi i managed to make it work by wrapping it in a form element (see below). will close issue - i may take a stab at implementing it but won't get to it for at least a few days. will let you know if i have further q's about it. thanks!

```
        {{#form.element label="Flag Filters" property="flags" useIcons=false as |el|}}
          {{#power-select-multiple
            options=flagFilters
            selected=selectedFlags
            searchField="Flags"
            placeholder="Select flags filters"
            onchange=(action (mut selectedFlags))
            as |flagFilter|
          }}
            {{flagFilter.label}}
          {{/power-select-multiple}}
        {{/form.element}}
```
