### ISSUE TITLE
selectChoose not working

### ISSUE THREAD

**Issue by ashrafhasson** [kaliber5/ember-bootstrap-power-select#19]
When using `selectChoose` helper in an acceptance test, it doesn't seem to select anything regardless of how you setup the `ember-bootstrap-power-select` component and without any impact in terms of specifying the csspath.

When used in the pure `power-select` way, things work fine.

**Comment by jrock2004** [comment]
@ashrafhasson I am having same issue with setting a selected. Works fine with regular power select but with this addon, it does not work

**Comment by simonihmig** [comment]
Sorry for the late answer, I missed this somehow. 

This should definitely work, we are writing acceptance tests using this addon... There is little information how you do it, can you post the relevant code snippets?

**Comment by jelhan** [comment]
I'm closing this now due to missing feedback.
