### ISSUE TITLE
ember-bootstrap-power-select should yield two parameters

### ISSUE THREAD

**Issue by Titinux** [kaliber5/ember-bootstrap-power-select#25]
Hi,

ember-power-selected yield two parameters when used with the block syntax. The first one is the selected item and the second one is a search object.

This is explained in the power-selected doc http://ember-power-select.com/docs/the-search at the "Using the search term inside the block" paragraph.

So I think the second parameter should be added on this lines (same for multiple version of the component)

https://github.com/kaliber5/ember-bootstrap-power-select/blob/4e1ff75ac8aaf5e74829fecd2cdc4a2877078a52/addon/templates/components/bs-form/element/control/power-select.hbs#L23

https://github.com/kaliber5/ember-bootstrap-power-select/blob/4e1ff75ac8aaf5e74829fecd2cdc4a2877078a52/addon/templates/components/bs-form/element/control/power-select.hbs#L25

If this is ok, I can make a push request if you want.

**Comment by simonihmig** [comment]
@Titinux Seems good to me, a PR is certainly welcome!
