### ISSUE TITLE
Selected attribute is not working

### ISSUE THREAD

**Issue by jrock2004** [kaliber5/ember-bootstrap-power-select#28]
If I use regular ember power select by itself it renders just fine

```
{{#power-select
      class="mobile-carriers-dropdown-container"
      label="Your mobile phone carrier"
      options=mobilePhoneCarriers
      selected=selectedPhoneCarrier
      placeholder="Choose carrier"
      searchEnabled=false
      onchange=(action "updateCarrier") as |name|}}

      {{name.name}}

    {{/power-select}}
```

Now trying to use your plugin and it does not work

```
{{#form.element
    class="mobile-carriers-dropdown-container"
    selected=selectedPhoneCarrier
    controlType="power-select"
    label="Your mobile phone carrier"
    options=mobilePhoneCarriers
    placeholder="Choose carrier"
    property="mobilePhoneCarrier" as |el|}}

    {{#el.control searchEnabled=false allowClear=true as |item|}}
      {{item.name}}
    {{/el.control}}

  {{/form.element}}
```

I hit the dropdown and I see the options. But when the page is loaded the select just shows the placeholder text. Thoughts

**Comment by simonihmig** [comment]
There is no `selected` property for `form.element`, as you have used it in 2nd example!

You have to use either `property` (to fetch the given property name from the form's `model`) or directly `value`. See the API docs https://www.ember-bootstrap.com/api/classes/Components.FormElement.html.
