### ISSUE TITLE
Search isn't enabled with @searchEnabled=true

### ISSUE THREAD

**Issue by egallup02360** [kaliber5/ember-bootstrap-power-select#293]
```html
<form.element @searchEnabled=true @searchField="company.name" @controlType="power-select" @property="company" @label="Company" @options={{@model}} @optionLabelPath="company.name" />
```

I expect there to be a search field displayed, but I only get the list of items to select from.

**Comment by jelhan** [comment]
Haven't tested it, but I think the `@searchEnabled` and `@searchField` arguments mist be set on the `<PowerSelect>` component. It is yielded as `control` component.

```
<form.element @controlType="power-select" @property="company" @label="Company" @options={{@model}} @optionLabelPath="company.name" as |el|>
  <el.control @searchEnabled={{true}} @searchField="company.name" />
<form.element>
```

**Comment by egallup02360** [comment]
> Haven't tested it, but I think the `@searchEnabled` and `@searchField` arguments mist be set on the `<PowerSelect>` component. It is yielded as `control` component.
> 
> ```
> <form.element @controlType="power-select" @property="company" @label="Company" @options={{@model}} @optionLabelPath="company.name" as |el|>
>   <el.control @searchEnabled={{true}} @searchField="company.name" />
> <form.element>
> ```

Thanks for the reply @jelhan. I tried this approach, but I end up with a blank select field whenever I select a value after making this change, but I do end up getting the search field so that's a plus I suppose.

What I have now is

```html
<form.element @searchEnabled=true @searchField="company.name" @onChange={{this.changeCompany}} @controlType="power-select" @property="company" @label="Company" @options={{@model}} @optionLabelPath="company.name" as |el|>
  <el.control @searchEnabled={{true}} @searchField="company.name" @optionLabelPath="company.name" />
</form.element>
```

Not sure if `@optionLabelPath` is needed on the control as well, but it doesn't give the expected result with or without it there.

**Comment by jelhan** [comment]
> I tried this approach, but I end up with a blank select field whenever I select a value after making this change

You are passing a custom `onChange` event handler. By doing so, you are opting out of the default handling of `@property` on form's `@model`. The issue you are describing sounds being related to that one.
