### ISSUE TITLE
hasBlock deprecation warning

### ISSUE THREAD

**Issue by sdellisImpinj** [kaliber5/ember-bootstrap-power-select#297]
In newer versions of ember (3.26+), I see the following deprecation warnings:

DEPRECATION: `hasBlock` is deprecated. Use `has-block` instead. ('ember-bootstrap-power-select/components/bs-form/element/control/power-select-multiple.hbs'
DEPRECATION: `hasBlock` is deprecated. Use `has-block` instead. ('ember-bootstrap-power-select/components/bs-form/element/control/power-select.hbs'

This deprecation is preventing me from upgrading to Ember 4.0.0. In theory this should be a simple swap from using hasBlock to has-block.

**Comment by jelhan** [comment]
Which version of Ember Bootstrap are you using? This should have been fixed long ago. Maybe only on v5.

**Comment by sdellisImpinj** [comment]
@jelhan 
I'm on ember-bootstrap 4.9 (the version before 5.0) and ember-bootstrap-power-select 3.0.1. Why does the ember-bootstrap version matter, though? The error appears to be coming from ember-bootstrap-power-select, not ember-bootstrap. Or am I misunderstanding something?

**Comment by jelhan** [comment]
I'm sorry. I missed that this is about `ember-bootstrap-power-select`. You are right that this app needs to be updated. It uses `has-block` at two places:

https://github.com/kaliber5/ember-bootstrap-power-select/blob/e1b760ad3d6b541552b569197b24eb1803542f14/addon/components/bs-form/element/control/power-select-multiple.hbs#L60

https://github.com/kaliber5/ember-bootstrap-power-select/blob/e1b760ad3d6b541552b569197b24eb1803542f14/addon/components/bs-form/element/control/power-select.hbs#L61

Merge request is very welcome.

**Comment by jelhan** [comment]
Fixed by #298. Not released yet.
