### ISSUE TITLE
selectedItemComponent does not work

### ISSUE THREAD

**Issue by mwalper** [kaliber5/ember-bootstrap-power-select#33]
Hi,
i'm trying to use the [selectedItemComponent](https://ember-power-select.com/docs/the-trigger) property on the el.control without success.
What i want to accomplish, is to render a different output on the selected Item, compared to the rendering in the select Box.

I first tried to add the selectedItemComponent property to the form.element and then to the element.control itself. Both without success.

```
{{#form.element
	controlType="power-select"
	label=(t "statusinfo.model.statusicon")
	property="statusicon"
	options=(sort-by "position:asc" statusiconList)
	placeholder=(t "common.select")
	as |el|
}}
	{{#el.control
		searchEnabled=false
		selectedItemComponent="statusinfo-ps-statusicon-select"
		as |option|
	}}
		<img src="/assets/img/status/{{option.icon}}" class="w40 inline-object mr5">
		{{option.nameDe}}
	{{/el.control}}
{{/form.element}}
```

Any ideas?

**Comment by simonihmig** [comment]
Should be fixed by #31
