### ISSUE TITLE
Opening dropdown does not put focus on search box

### ISSUE THREAD

**Issue by psteininger** [kaliber5/ember-bootstrap-power-select#39]
When opening the dropdown, the search box does not get a focus. This is confusing when trying to search a list form a task. The focus remains on the drop-down. Also, the dropdown does not get the "form-control" class even if set explicitly.
![image](https://user-images.githubusercontent.com/411705/42381540-ab715c80-8131-11e8-9a0b-e4e072dc6632.png)

see that the dropdown is smaller in height than the field above

**Comment by simonihmig** [comment]
Are you using Ember 3.2? Just stumbled upon this: https://github.com/emberjs/ember.js/issues/16800

**Comment by psteininger** [comment]
@simonihmig I am indeed using ember 3.2, so I will close this issue, and hope for a resolution down the road in form of ember upgrade.
