### ISSUE TITLE
With searchEnabled=false the search input still appears

### ISSUE THREAD

**Issue by alex-jgr** [kaliber5/ember-bootstrap-power-select#73]
`{{form.element
   controlType="power-select"
   placeholder="Day..."
   property="selectedDay"
   searchEnabled=false
   options=days}}`

![select-day](https://user-images.githubusercontent.com/5990093/50453575-284ee600-094a-11e9-8e92-a87f7ce66d2e.png)

**Comment by simonihmig** [comment]
Yes, the `form.element` component does not know anything about power-select options. You need to set it on the yielded control component, like in these examples: https://github.com/kaliber5/ember-bootstrap-power-select#advanced-usage

```
{{#form.element controlType="power-select" placeholder="Day..." property="selectedDay" options=days as |el|}}
  {{#el.control searchEnabled=false}}
  ...
```
