### ISSUE TITLE
ember-changeset hasMany relationship error

### ISSUE THREAD

**Issue by sinankeskin** [kaliber5/ember-bootstrap-power-select#83]
Hi.

We are using latest version ember-changeset (2.1.2). We searched everywhere but we couldn't find the answer. Basically we have the same issue with #41  but with hasMany relationship.

This code is not working and throws **power-select-multiple.js:95 Uncaught TypeError: (select.selected || []).slice is not a function**

```handlebars
      {{#form.element
        controlType="power-select-multiple"
        property="cities"
        placeholder="Select"
        label=(t "service_provider.cities")
        options=cities as |el|
      }}
        {{#el.control searchPlaceholder="Search..." as |item|}}
          {{item.name}}
        {{/el.control}}
      {{/form.element}}
```

If we change the code like this [as he suggests](https://github.com/kaliber5/ember-bootstrap-power-select/issues/41#issuecomment-404173255) everything is ok but this time changes doesn't apply to underlying object which changeset save doesn't send changed elements on serialized json.

```handlebars
      {{#form.element
        controlType="power-select-multiple"
        property="cities.content"
        placeholder="Select"
        label=(t "service_provider.cities")
        options=cities as |el|
      }}
        {{#el.control searchPlaceholder="Search..." as |item|}}
          {{item.name}}
        {{/el.control}}
      {{/form.element}}
```

I couldn't find any answer that ember-changeset has a support for hasMany relationship. Some says yes latest version does, some says doesn't or is this problem occuring because of power-select?

Is there any workaround to suggest?

Thanks.

**Comment by jelhan** [comment]
I'm sorry that you haven't got a reply for such a long time. Are you still able to reproduce this bug using recent versions for `ember-changeset`, `ember-power-select` and `ember-bootstrap-power-select`?

**Comment by sinankeskin** [comment]
Hi.

If i upgrade ember-bootstrap-power-select to 2.0.0 some other error comes up but looks like this bug has been resolved somehow.

Working as supposed to be now.

Thank you.
Closing.
