### ISSUE TITLE
Options is a list of objects but property will be saved as string

### ISSUE THREAD

**Issue by freyjameetsmel** [kaliber5/ember-bootstrap-power-select#91]
I have the following use case: 

We have a user form with a select for the country. The **options** for this select **is a list of objects** with a country code and a translation for each object. But only the country code will be saved in the end. 

This is our current setup: 
```
<form.element @controlType="power-select" 
              @property="address.country" 
              @label={{t 'user.country'}} 
              @options={{this.countryOptions}} 
              @optionLabelPath="translation" as |elem|>
    <elem.control @searchEnabled={{true}} @searchField="translation"/>
</form.element>
```

With the following properties:
```
model.address.country = 'DE';
countryOptions = [
                      {code: 'DE', translation: 'Germany'},
                      {code: 'IT', translation: 'Italy'},
                      {code: 'FR', translation: 'France'},
                      ...
                 ];
```

**We have the following issues:** 

1) If the user has already a country selected (initial state) it won't show up in the select. Probably as it is not an object. I tried to set the selected property manually as an object but this also doesn't seem to work. 

2) If you select a new country, it shows up correctly in the select. But the property will be saved wrong, as we only save the country code here. I tried to work with an onChange-Action that sets the selected property manually but it only resulted in an empty select. 

Is there a way to handle this properly? 
If you need more information, let me know!

Thx, Mel

Current ember setting: 

    "ember-cli": "3.15.0-beta.1",
    "ember-data": "~3.14.0",
    "ember-source": "3.14.1",
    "ember-bootstrap": "^3.1.0",
    "ember-bootstrap-power-select": "^2.0.0",

**Comment by jelhan** [comment]
Any reasons you are wrapping the code and translation in an object and using that one as `options`? I'm mostly doing something like this:

```hbs
<form.element
  @controlType="power-select" 
  @property="address.country" 
  @label={{t 'user.country'}} 
  @options={{array "DE" "IT" "FR"}} 
  as |elem|
>
  {{#let (hash DE="Germany" IT="Italy" FR="France") as |translations|}}
    <elem.control @searchEnabled={{true}} @searchField="translation" as |option|>
     {{get translations option}}
    </elem.control>
  {{/let}}
</form.element>
```

Of course I don't construct the translations object in the template but in backing JavaScript file. Just included that one for simplicity.

**Comment by freyjameetsmel** [comment]
@jelhan
We handle the translations for the countries and other lists in the backend. Mostly because we might need those lists for other endpoints and not just only in the frontend.

Your approach looks good. Thank you. I'll try that. It will work for our use case. 

But what about those use cases where you want to set something else along with the selected property? I assume this could be handled with an observer?

**Comment by jelhan** [comment]
I won't recommend to use an observer. Either use a computed property with getter and setter or override default `onChange` action. Let me know if this approach works out for you. Will close the ticket for now. Feel free to reopen if it's not working well.
