### ISSUE TITLE
make dropdown required

### ISSUE THREAD

**Issue by michonite** [kaliber5/ember-bootstrap-power-select#96]
the empty dropdown option doesn't trigger the required flag/prompt

**Comment by jelhan** [comment]
I can't follow. Can you please elaborate a little bit? A code snippet would be helpful as well.

**Comment by mistahenry** [comment]
@jelhan I believe he's saying that `@required` is not supported like it is in the base `ember-bootstrap` form elements. I just encountered the same in a project of my own

**Comment by jelhan** [comment]
`@required` argument of `<form.element>` has been deprecated in Ember Bootstrap v3 and is removed in v4. It was only used to set the `required` HTML attribute on an `<input>` or `<textarea>` form control.

Ember Power Select does not support something similar. It does not have a `@required` argument nor uses a HTML tag, which supports `required` attribute. So I wouldn't be sure what this should do at all.
